homepage:
    path: /
    controller: App\Controller\HomeController::view
    methods: GET

product:
    path: /product/{id}
    controller: App\Controller\ProductController::view
    defaults: { id: 1 }
